### ISSUE TITLE
Deploy to Azure Button をつけたい

### ISSUE THREAD

**Issue by nnasaki** [NT-D/AzureML_Recommend_Sample#2]
こんな感じのボタンを追加して、github の README からデプロイできると良いなーと思いました。

![image](https://cloud.githubusercontent.com/assets/875216/8034707/2c206b42-0e25-11e5-9a27-8b376f14919e.png)

詳細は下記の通り。Application Properties も設定できるようです。
- [Deploy to Azure Button for Azure Websites | Microsoft Azure Blog](http://azure.microsoft.com/blog/2014/11/13/deploy-to-azure-button-for-azure-websites-2/)
- [Deploy to Azure ボタンについての詳しいまとめ](https://r2.ag/deploy-to-azure-button/)

**Comment by masa-fleet** [comment]
おかげさまで解決しました〜！
ありがとうございました。
